w

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -38,7 +38,10 @@ jobs:
           # Compare and throw error if are equal
           echo "Last hash: ${LAST_COMMIT_HASH}"
           echo "New hash: ${NEW_COMMIT_HASH}"
-          [[ "${NEW_COMMIT_HASH}" == "${LAST_COMMIT_HASH}" ]] && echo "Error: You can't execute another release with the same commit hash that the last one" && exit 2
+          if [ "${NEW_COMMIT_HASH}" == "${LAST_COMMIT_HASH}" ]; then
+            echo "Error: You can't execute another release with the same commit hash that the last one"
+            exit 1
+          fi
       - name: Release
         uses: softprops/action-gh-release@v1
         with:
